# Exception

e = Exception(1, 2, 3)
print(e.args)

e = StopIteration()
print(e.args)
